name = "shipnova-api"
main = "src/index.js"
compatibility_date = "2026-08-31"

[assets]
directory = "./frontend"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "shipnova"
database_id = "ee94c087-e68b-49ab-8c6f-c725a39cebe4"
migrations_dir = "migrations"
